### ISSUE TITLE
Read Chapter 1 in PRS book

### ISSUE THREAD

**Issue by 9health** [9health/moviegeek#11]
Input
- Free on Manning [Chapter 1. What is a recommender?](https://livebook.manning.com/book/practical-recommender-systems/chapter-1)

Output
- Understand chapter 1

Time
- 2 hours

History
- 2022/Dec/19: newly create
- 2022/Dec/21: Add Time section

**Comment by 9health** [comment]
Hello @quangvv9Life,

Tớ thấy đọc Chapter 1 như vậy qua qua cũng hiểu sơ sơ rồi =.=

Có gì xem lại sau vậy.

Task này tớ chuyển thành Review nhé!!!

Tổng cộng tớ dùng hết 2 tiếng nhé!!!

**Comment by quangvv9Life** [comment]
Hi @9health 

OK Hải ởi nhưng mà tuần trước plan đọc Chương 9  và chương 7 sao lại đọc Chương 1 nhỉ?

BR
Quang

**Comment by 9health** [comment]
Hello @quangvv9Life,

À như tớ đã giải thích lần trước là do Chương 9 và Chương 7 đọc khó quá như leo núi dốc 60 độ vậy.

Tớ nghĩ cứ tập dần với dốc 15 độ hay 20 độ cho quen đã rồi leo 60 độ sau cũng được =.=

Chứ mình không tập luyện gì mà đòi leo ngay Himalaya chẳng hạn cũng chết =.=

Thực ra Phú Sĩ với Fansipan thì còn được hic.

Cảm ơn Quang đã hiểu!!!

**Comment by 9health** [comment]
Hello @quangvv9Life,

Đã 4 ngày kể từ khi comment rùi.

Tớ move task này thành `Done` nha!!!

Thanks Quang!!!
