### ISSUE TITLE
Read and Check Code, Log of Chapter 4 - Rating

### ISSUE THREAD

**Issue by 9health** [9health/moviegeek#19]
# Input
- Black-box Chapter 4 on Manning
   - https://livebook.manning.com/book/practical-recommender-systems/chapter-4

# Output
- Understand what is implicit rating, explicit rating, how to calculate implicit rating from user's behaviors.
- Understand Django builder implicit rating calculator
  - Database
  - Python running log file
  - Check movie rating on after running implicit rating calculator

# Time
- 4 hours

# History
- 2022/Dec/28: Newly create
- 2022/Dec/31: Add reading time

**Comment by quangvv9Life** [comment]
Hi Hải, @9health 

Phần này hôm 30/12/22 họp và Hải đã đi qua. Vậy định nghĩa của phần "understand" trong phần output là gì nhỉ ?

- Có thể là mình hiểu trong đầu? 
- có thể là tớ và Hải cùng hiểu? 
- có thể là có documents lại ? :-? 
- etc.

Hiện tại mình mới có meeting minute và các comment của Hải  về từng chương thôi. Vẫn hơi mù mờ, cùng trao đổi về phần output này nhé !!!

BR
Quang

**Comment by 9health** [comment]
Hello @quangvv9Life,

Cảm ơn Quang đã comment nhé @@.

- Về ý thứ nhất thì cái đấy đương nhiên phải có rùi @@. Hiểu trong đầu đã rồi mới nói cho người khác được.
- Về ý thứ 2 thì tớ nghĩ cái này nên có. Đương nhiên là sẽ có nhiều level hiểu =.=
  - Level 1: Đầu tiên là hiểu qua về nội dung
  - Level 2: Tiếp nữa là hiểu chi tiết hơn từng phần
  - Level 3: Tiếp nữa là hiểu cả source code có trong chương đấy
  - Level 4: Hiểu xem web app front-end, back-end chạy như thế nào
  - Level 5: Có thể modify được code tác giả theo ý mình, tất nhiền modify chỉ vài dòng tới chục dòng thôi
  - Level 6: Có thể viết lại được hết toàn bộ code!!! (Dựa vào miêu tả trong chương ý!!!)
  - Level 7: Có thể tự define ra cái mình cần giống như chương ý, tự code cái mình cần luôn @@.
  - Level 8: Có thể tự define ra cái mình cần như là cả quyển sách luôn @@, tự code từ đầu tới cuối luôn @@.
  - Theo tớ thì tùy từng giai đoạn, tùy mục đích, tùy thời gian mình có mà chọn ở Level nào @@.
    - Qua được Level 6 thì là mỹ mãn rùi @@.
    - Qua được Level 8 chắc gọi là Solution Architect rồi.
      - Cơ mà đến Level 8 rồi mà tự làm 1 mình như tác giả, 4 - 5 năm viết sách PRS (2015 - 2019) thì cũng lâu thật @@.
      - Đông người chắc nhanh hơn nhưng mà thường coder nói chuyện với nhau cũng khá khó. Có lẽ thế thui!!!
        - Vì những ý tưởng mới hoặc chưa rõ ràng thì người nghĩ và người implement trao đổi nhiều
          - Có khi miscommunication
          - Có khi xấu hơn nữa @@@@@.
          - Nên là thôi tự code, tự viết sách =.=
          - Chắc là quyển sách bác ý viết tớ nghĩ ngang với công lao bác í bỏ ra thôi.
            - Ví dụ 4 năm liên tục code, viết, thử, mỗi ngày 2 tiếng.
              - 1 tuần có 5 business days, làm 10 tiếng. 1 tháng có 20 business days, làm 40 tiếng :-?
              - 1 năm có 50 tuần, làm mất 500 tiếng.
              - 4 năm là 2,000 tiếng ^_^
              - Quy ra số tháng lương thì là 4 tháng bác ý làm bằng 1 tháng người khác làm full-time.
              - Vậy thì 4 năm bác ý viết và làm sách bằng 1 năm người khác làm full-time @_@.
              - Vị chi NXB trả 1 năm tiền lương bác ý là hợp lý ^_^

Sorry Quang chắc là tớ viết dài nên là đọc hay bị lan man, mất nội dung @@.

May mà Quang cũng hỏi lại tớ để trao đổi thêm.

Và có lẽ trực tiếp hay hơn là online @@@@@ Vì vẽ ra giấy chẳng hạn... Và cũng lâu thật :-S.

Cơ mà thôi cứ dần dần, tớ nghĩ mọi thứ sẽ okay.

Cảm ơn Quang!!!
