### ISSUE TITLE
Create a Linux VM on Azure

### ISSUE THREAD

**Issue by 9health** [9health/moviegeek#7]
Output
- Create a free Azure Linux VM in Azure 12-month free services.
- A Wiki document.
  - [[11] Azure VM Create](https://github.com/9health/moviegeek/wiki/%5B11%5D-Azure-VM-Create)

Note
- 2022/Dec/15 Add Wiki link

**Comment by 9health** [comment]
Hello @quangvv9Life,

Task này cũng khá là okay rùi.

Output đầy đủ theo ý tớ rùi.

Tớ sẽ chuyển sang trạng thái `Done` nhé!!!

**Comment by quangvv9Life** [comment]
Hi @9health ,

Cái này có thể viết script lại để khi chuyển sang credit Azure thì tự chạy cho nhanh không Hải nhỉ ? đỡ phải setup từ đầu mất thời gian 

BR
Quang

**Comment by 9health** [comment]
Hello @quangvv9Life,

Cảm ơn Quang đã comment.

Cái này đã là simple nhất rùi đấy Quang @@.

Nếu mà Quang thích viết kiểu `pwsh` thay vì `bash` như tớ thì sửa lại command 1 xíu.

Script thì cũng là bọc lại của command tạo máy ảo thui!!!

Đảm bảo dùng cái này sẽ

> tự chạy cho nhanh không Hải nhỉ ? đỡ phải setup từ đầu mất thời gian

Quang nhé!!!

Thanks Quang!!!
